### ISSUE TITLE
Add repeat function

### ISSUE THREAD

**Issue by perry** [incuna/incuna-sass#8]
Via @henrahmagix

``` sass
@function repeat($str, $times: 3, $join: '')
    $longStr: ''
    @for $i from 1 through $times
        @if $i > 1
            $longStr: $longStr + $join + $str
        @else
            $longStr: $longStr + $str
    @return #{$longStr}

body
    content: repeat(foo bar baz)
    content: repeat('gum foo', 5, ', ')
```

``` css
body {
  content: foo bar bazfoo bar bazfoo bar baz;
  content: gum foo, gum foo, gum foo, gum foo, gum foo;
}
```
